### ISSUE TITLE
bracket not match

### ISSUE THREAD

**Issue by XIGGG** [mika-cn/mathml2latex#11]
Hello, thanks for this package.
I am using your package to convert the following MathML to TeX:
`<math xmlns="http://www.w3.org/1998/Math/MathML"><mo>(</mo><mn>3</mn><msup><mi>a</mi><mrow><mn>2</mn></mrow></msup><mi>b</mi><msup><mo>)</mo><mrow><mn>2</mn></mrow></msup><mo>÷</mo><mo>(</mo><mo>−</mo><mn>9</mn><msup><mi>a</mi><mrow><mn>4</mn></mrow></msup><msup><mi>b</mi><mrow><mn>2</mn></mrow></msup><mo>)</mo><mo>⋅</mo><mo>(</mo><mo>−</mo><mn>2</mn><mi>a</mi><msup><mi>b</mi><mrow><mn>2</mn></mrow></msup><mo>)</mo></math>`

The package converts this to:
`\left(3a^{2}b2^{undefined}\div\left(−9a^{4}b^{2}\right)\cdot\left(−2ab^{2}\right)\right.`

and console.error
![image](https://user-images.githubusercontent.com/16800903/120312214-04f2a700-c30b-11eb-8cd3-cfedf330af6d.png)

**Comment by mika-cn** [comment]
The second `<msub>`'s content `<msup><mo>)</mo><mrow><mn>2</mn></mrow></msup>` is so weird, it means the square of ")" ? Although this MathML may display just fine on browser, It's content makes no sense. What you want to express is the square of "(...)". 

The fixed code with indentations:

```html
  <msup>
    <!-- the base part, (...) -->
    <mrow>
      <mo>(</mo>
        <mn>3</mn>
        <msup>
          <mi>a</mi>
          <mrow><mn>2</mn></mrow>
        </msup>
        <mi>b</mi>
      <mo>)</mo>
    </mrow>

   <!-- the square -->
    <mrow><mn>2</mn></mrow>
  </msup> 
```

**Comment by XIGGG** [comment]
Thanks for your answer!
