### ISSUE TITLE
可以支持将一段文本内的所有mathml都转为latex么

### ISSUE THREAD

**Issue by BolinWang** [mika-cn/mathml2latex#12]
比如：
`<p><math xmlns="http://www.w3.org/1998/Math/MathML"><mroot><mn>3</mn><mn>2</mn></mroot></math></p><p><math xmlns="http://www.w3.org/1998/Math/MathML"><mroot><mn>3</mn><mn>2</mn></mroot></math></p>`

结果：应该是2个公式才对~

**Comment by mika-cn** [comment]
这个不支持的。你完全可以通过下面这段代码完成同样的事

```javascript
const formulas = [].map.call(document.querySelectorAll('math'), (node) => {
  return MathML2LaTeX.convert(node.outerHTML)
});
```

**Comment by mika-cn** [comment]
如果你的运行环境没有 DOM 接口的话，实现这个也没有意义啊，假如说可以返回多个公式，那你也得判断，哪个公式属于哪段 HTML 的吧。

**Comment by BolinWang** [comment]
> 如果你的运行环境没有 DOM 接口的话，实现这个也没有意义啊，假如说可以返回多个公式，那你也得判断，哪个公式属于哪段 HTML 的吧。

我已经换了思路了，我把富文本中所有dom节点做遍历，然后根据文本、图片、公式等依次解析为数据，遍历到公式的（如math标签等）调用你的解析方法完成，最后组装好所有数据
