### ISSUE TITLE
matrix don't work properly

### ISSUE THREAD

**Issue by Wenangsani** [mika-cn/mathml2latex#17]
I convert from this
```
<mtable>
   <mtr>
      <mtd>
         <mn>1</mn>
         <mo>⋅</mo>
         <mn>2</mn>
      </mtd>
   </mtr>
   <mtr>
      <mtd>
         <mn>2</mn>
         <mo>⋅</mo>
         <mn>3</mn>
      </mtd>
   </mtr>
</mtable>
```
become this
`
\begin{matrix} 1\\2\\ \end{matrix}
`

my expectation
`
\begin{matrix}1\cdot2\\2\cdot3\end{matrix}
`
thanks.

**Comment by mika-cn** [comment]
@Wenangsani

Thanks for the feedback.

I can reproduce this issue, there's something wrong about `<mtd>`'s render function. I'll fix it on next version.

**Comment by mika-cn** [comment]
The new version has been published.
